environment:

  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    WITH_COMPILER: "cmd /E:ON /V:ON /C ..\\appveyor\\run_with_compiler.cmd"

  matrix:

    # Pre-installed Python versions, which Appveyor may upgrade to
    # a later point release.
    # See: http://www.appveyor.com/docs/installed-software#python

    - PYTHON: "C:\\Python37"
      PYTHON_VERSION: "3.7.0"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: "3.7.0"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python38"
      PYTHON_VERSION: "3.8.0"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python38-x64"
      PYTHON_VERSION: "3.8.0"
      PYTHON_ARCH: "64"

branches:

    only:
        - master

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "powershell appveyor\\install.ps1"
  - "%CMD_IN_ENV% python -m pip install pygame pytest numpy"
  - "%CMD_IN_ENV% python setup.py install"
  - cd accelerate
  - "%CMD_IN_ENV% python setup.py install"
  - cd ..

build_script:
  - cd accelerate
  - "ECHO %WITH_COMPILER% %PYTHON%/python.exe setup.py bdist_wheel"
  - "%WITH_COMPILER% %PYTHON%/python.exe setup.py bdist_wheel"
  - cd ..

test_script:
  - "%CMD_IN_ENV% pytest -sv tests/test_core.py"

artifacts:
  - path: accelerate\dist\*
    name: dist-accel
  - path: dist\*
    name: dist

#on_success:
#  - TODO: upload the content of dist/*.whl to a public wheelhouse
